ALTER TABLE "teams"
  ADD COLUMN "participation_type" VARCHAR(30) NOT NULL DEFAULT 'Team / Group',
  ADD COLUMN "participant_category" VARCHAR(60),
  ADD COLUMN "participation_level" VARCHAR(40),
  ADD COLUMN "institution_type" VARCHAR(80),
  ADD COLUMN "affiliation_pin_code" VARCHAR(10),
  ADD COLUMN "affiliation_city" VARCHAR(100),
  ADD COLUMN "affiliation_state" VARCHAR(100),
  ADD COLUMN "institution_email" VARCHAR(255),
  ADD COLUMN "institution_phone" VARCHAR(15),
  ADD COLUMN "class_level" VARCHAR(50),
  ADD COLUMN "degree_programme" VARCHAR(150),
  ADD COLUMN "department_branch" VARCHAR(150),
  ADD COLUMN "year_of_study" VARCHAR(60),
  ADD COLUMN "coordinator_name" VARCHAR(150),
  ADD COLUMN "coordinator_email" VARCHAR(255),
  ADD COLUMN "coordinator_phone" VARCHAR(15),
  ADD COLUMN "designation_role" VARCHAR(150),
  ADD COLUMN "department_division" VARCHAR(150),
  ADD COLUMN "official_org_email" VARCHAR(255),
  ADD COLUMN "org_contact_phone" VARCHAR(15),
  ADD COLUMN "mentor_name" VARCHAR(150),
  ADD COLUMN "mentor_designation" VARCHAR(150),
  ADD COLUMN "mentor_email" VARCHAR(255),
  ADD COLUMN "mentor_phone" VARCHAR(15);